<?php

namespace Tests\Unit\Http\Requests;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\PlacementRequest
 */
class PlacementRequestTest extends TestCase
{
    /** @var \App\Http\Requests\PlacementRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\PlacementRequest();
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'experience' => 'max:255',
            'instruments' => 'max:255',
            'skill_pitch' => 'nullable|sometimes|min:1|max:5',
            'skill_harmony' => 'nullable|sometimes|min:1|max:5',
            'skill_performance' => 'nullable|sometimes|min:1|max:5',
            'skill_sightreading' => 'nullable|sometimes|min:1|max:5',
            'voice_tone' => 'nullable|sometimes|min:1|max:3',
            'voice_part_id' => '',
        ], $actual);
    }

    // test cases...
}
