<?php

namespace Tests\Unit\Http\Requests;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\RiserStackRequest
 */
class RiserStackRequestTest extends TestCase
{
    /** @var \App\Http\Requests\RiserStackRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\RiserStackRequest();
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'title' => 'required|max:255',
            'rows' => 'required|integer|min:1|max:255',
            'columns' => 'required|integer|min:1|max:255',
            'front_row_length' => 'required|integer|min:1|max:255',
            'singer_positions' => 'required|json',
            'front_row_on_floor' => '',
        ], $actual);
    }

    // test cases...
}
