<?php

namespace Tests\Unit\Http\Requests;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\SingerRequest
 */
class SingerRequestTest extends TestCase
{
    /** @var \App\Http\Requests\SingerRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\SingerRequest();
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'email' => [
                'required',
            ],
            'user_roles' => [
                'array',
                'exists:roles,id',
            ],
            'first_name' => [
                'required',
                'max:127',
            ],
            'last_name' => [
                'required',
                'max:127',
            ],
            'onboarding_enabled' => [
                'boolean',
            ],
            'voice_part_id' => [
                '',
            ],
            'password' => [
                'sometimes',
                'nullable',
                'min:8',
                'max:255',
                'confirmed',
            ],
            'avatar' => [
                'file',
                'mimetypes:image/jpeg,image/png',
                'max:10240',
            ],
        ], $actual);
    }

    // test cases...
}
