<?php

namespace Tests\Unit\Http\Requests;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\UserGroupRequest
 */
class UserGroupRequestTest extends TestCase
{
    /** @var \App\Http\Requests\UserGroupRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\UserGroupRequest();
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'slug' => [
                'required',
                'max:255',
            ],
            'title' => [
                'required',
                'max:255',
            ],
            'list_type' => [
                'required',
            ],
            'recipient_roles' => [
                '',
            ],
            'recipient_voice_parts' => [
                '',
            ],
            'recipient_users' => [
                '',
            ],
            'recipient_singer_categories' => [
                '',
            ],
            'sender_roles' => [
                '',
            ],
            'sender_voice_parts' => [
                '',
            ],
            'sender_users' => [
                '',
            ],
            'sender_singer_categories' => [
                '',
            ],
        ], $actual);
    }

    // test cases...
}
