<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\AttendanceController
 */
class AttendanceControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $event = \App\Models\Event::factory()->create();

        $response = $this->get(route('events.attendances.index', [$event]));

        $response->assertOk();
        $response->assertViewIs('events.attendances.index');
        $response->assertViewHas('event');
        $response->assertViewHas('singers');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_all_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $event = \App\Models\Event::factory()->create();

        $response = $this->post(route('events.attendances.updateAll', [$event]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('events.show', ['event' => $event]));

        // TODO: perform additional assertions
    }

    // test cases...
}
