<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\AttendanceReportController
 */
class AttendanceReportControllerTest extends TestCase
{
	/**
	 * @test
	 */
	public function invoke_returns_an_ok_response()
	{
		$this->markTestIncomplete(
			'This test case was generated by Shift. When you are ready, remove this line and complete this test case.',
		);

		$response = $this->get(route('events.reports.attendance'));

		$response->assertOk();
		$response->assertViewIs('events.reports.attendance');
		$response->assertViewHas('voice_parts');
		$response->assertViewHas('events');
		$response->assertViewHas('filters');
		$response->assertViewHas('avg_singers_per_event');
		$response->assertViewHas('avg_events_per_singer');

		// TODO: perform additional assertions
	}

	// test cases...
}
