<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\DashController
 */
class DashControllerTest extends TestCase
{
    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('dash'));

        $response->assertOk();
        $response->assertViewIs('dash');
        $response->assertViewHas('birthdays');
        $response->assertViewHas('empty_dobs');
        $response->assertViewHas('songs');
        $response->assertViewHas('events');

        // TODO: perform additional assertions
    }

    // test cases...
}
