<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\DeleteRecurringEventController
 */
class DeleteRecurringEventControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function invoke_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $event = \App\Models\Event::factory()->create();

        $response = $this->get(route('events.delete-recurring', [$event, 'mode' => $mode]));

        $response->assertRedirect(route('events.index'));

        // TODO: perform additional assertions
    }

    // test cases...
}
