<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\FolderController
 */
class FolderControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('folders.create'));

        $response->assertOk();
        $response->assertViewIs('folders.create');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $folder = \App\Models\Folder::factory()->create();

        $response = $this->delete(route('folders.destroy', [$folder]));

        $response->assertRedirect(route('folders.index'));
        $this->assertDeleted($folders);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $folder = \App\Models\Folder::factory()->create();

        $response = $this->get(route('folders.edit', [$folder]));

        $response->assertOk();
        $response->assertViewIs('folders.edit');
        $response->assertViewHas('folder');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('folders.index'));

        $response->assertOk();
        $response->assertViewIs('folders.index');
        $response->assertViewHas('folders');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $folder = \App\Models\Folder::factory()->create();

        $response = $this->get(route('folders.show', [$folder]));

        $response->assertOk();
        $response->assertViewIs('folders.show');
        $response->assertViewHas('folder');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('folders.store'), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('folders.index'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $folder = \App\Models\Folder::factory()->create();

        $response = $this->put(route('folders.update', [$folder]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('folders.index'));

        // TODO: perform additional assertions
    }

    // test cases...
}
