<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\ImpersonateUserController
 */
class ImpersonateUserControllerTest extends TestCase
{
    /**
     * @test
     */
    public function start_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = \App\Models\User::factory()->create();

        $response = $this->get(route('users.impersonate', [$user]));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function stop_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('impersonation.stop'));

        $response->assertRedirect(withErrors(['You have been impersonating another user for too long. The maximum is 1 hour for security reasons. Please log in again.']));

        // TODO: perform additional assertions
    }

    // test cases...
}
