<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\SingerPlacementController
 */
class SingerPlacementControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $singer = \App\Models\Singer::factory()->create();

        $response = $this->get(route('singers.placements.create', [$singer]));

        $response->assertOk();
        $response->assertViewIs('singers.createplacement');
        $response->assertViewHas('singer');
        $response->assertViewHas('voice_parts');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $singer = \App\Models\Singer::factory()->create();
        $placement = \App\Models\Placement::factory()->create();

        $response = $this->get(route('singers.placements.edit', [$singer, $placement]));

        $response->assertOk();
        $response->assertViewIs('singers.editplacement');
        $response->assertViewHas('singer');
        $response->assertViewHas('placement');
        $response->assertViewHas('voice_parts');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $singer = \App\Models\Singer::factory()->create();

        $response = $this->post(route('singers.placements.store', [$singer]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('singers.show', $singer));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $singer = \App\Models\Singer::factory()->create();
        $placement = \App\Models\Placement::factory()->create();

        $response = $this->put(route('singers.placements.update', [$singer, $placement]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('singers.show', $singer));

        // TODO: perform additional assertions
    }

    // test cases...
}
