<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\UpdateSingerCategoryController
 */
class UpdateSingerCategoryControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function invoke_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $singer = \App\Models\Singer::factory()->create();

        $response = $this->get(route('singers.categories.update', [$singer]));

        $response->assertRedirect(route('singers.index'));

        // TODO: perform additional assertions
    }

    // test cases...
}
