<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\VoicePartController
 */
class VoicePartControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('voice-parts.create'));

        $response->assertOk();
        $response->assertViewIs('voice-parts.create');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $voicePart = \App\Models\VoicePart::factory()->create();

        $response = $this->delete(route('voice-parts.destroy', [$voice_part]));

        $response->assertRedirect(route('voice-parts.index'));
        $this->assertDeleted($voiceParts);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $voicePart = \App\Models\VoicePart::factory()->create();

        $response = $this->get(route('voice-parts.edit', [$voice_part]));

        $response->assertOk();
        $response->assertViewIs();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('voice-parts.index'));

        $response->assertOk();
        $response->assertViewIs();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $voicePart = \App\Models\VoicePart::factory()->create();

        $response = $this->get(route('voice-parts.show', [$voice_part]));

        $response->assertOk();
        $response->assertViewIs();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('voice-parts.store'), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('voice-parts.show', $part));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $voicePart = \App\Models\VoicePart::factory()->create();

        $response = $this->put(route('voice-parts.update', [$voice_part]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('voice-parts.show', $voice_part));

        // TODO: perform additional assertions
    }

    // test cases...
}
